// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA734RaItBP5BV_JScfOQNiPiMqWLbZDUw',
    appId: '1:314355143779:web:ef0026291dab3d2a7c5456',
    messagingSenderId: '314355143779',
    projectId: 'databaseauthproject',
    authDomain: 'databaseauthproject.firebaseapp.com',
    databaseURL: 'https://databaseauthproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseauthproject.firebasestorage.app',
    measurementId: 'G-FYKRYZLQR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxTwHs1dUD6DiVy6taIXEtdyTm-VQmTTo',
    appId: '1:314355143779:android:320b7b0691ef57a27c5456',
    messagingSenderId: '314355143779',
    projectId: 'databaseauthproject',
    databaseURL: 'https://databaseauthproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseauthproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-uDgJu9U6wrQeVxEHOByK4i8n0HFYr8',
    appId: '1:314355143779:ios:203dd5d7e6f105ad7c5456',
    messagingSenderId: '314355143779',
    projectId: 'databaseauthproject',
    databaseURL: 'https://databaseauthproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseauthproject.firebasestorage.app',
    iosBundleId: 'com.example.profaritashion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-uDgJu9U6wrQeVxEHOByK4i8n0HFYr8',
    appId: '1:314355143779:ios:203dd5d7e6f105ad7c5456',
    messagingSenderId: '314355143779',
    projectId: 'databaseauthproject',
    databaseURL: 'https://databaseauthproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseauthproject.firebasestorage.app',
    iosBundleId: 'com.example.profaritashion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA734RaItBP5BV_JScfOQNiPiMqWLbZDUw',
    appId: '1:314355143779:web:f3a455e167f959587c5456',
    messagingSenderId: '314355143779',
    projectId: 'databaseauthproject',
    authDomain: 'databaseauthproject.firebaseapp.com',
    databaseURL: 'https://databaseauthproject-default-rtdb.firebaseio.com',
    storageBucket: 'databaseauthproject.firebasestorage.app',
    measurementId: 'G-SJ0DDYHVEF',
  );
}
